export const DATADRIVER = [
  {
    c_nopol: "H 9597 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Tri Hadi khashyadi",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9544 EE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Kusnadi",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9632 EE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Kusnin",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9530 EE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Eko Priyono",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9586 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Sunarto",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9599 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Rumidi",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9540 EE",
    c_kendaraan: "DUMP TRUCK",
    c_jenis: "DLH",
    c_driver: "Nur Kholis",
    c_fkali: 7,
  },
  {
    c_nopol: "H 9532 E",
    c_kendaraan: "DUMP TRUCK",
    c_jenis: "DLH",
    c_driver: "Sapardi",
    c_fkali: 7,
  },
  {
    c_nopol: "H 9598 GE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Soeprijanto",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9594 GE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DLH",
    c_driver: "Andre Fajar",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9577 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DINDAKOP",
    c_driver: "Arif",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9577 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DINDAKOP",
    c_driver: "Udin",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9677 AE",
    c_kendaraan: "CONTAINER",
    c_jenis: "DINDAKOP",
    c_driver: "Agung ",
    c_fkali: 6,
  },
  {
    c_nopol: "H 9759 KE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Supardi",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9786 LE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Susanto",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9764 KE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Kusriyanto",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9763 KE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Bejo Susilo",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9789 HE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Sunardi",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9761 KE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Budiyanto",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9762 KE ",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Sabiyono",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9787 LE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Zaenal",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9788 LE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Purwadi",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9711 ME",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Yoggi",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9895 HE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Suparno",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9760 KE",
    c_kendaraan: "RODA3",
    c_jenis: "PERKIM",
    c_driver: "Sunarto ",
    c_fkali: 1,
  },
  {
    c_nopol: "H 9565 GE",
    c_kendaraan: "PICKUP",
    c_jenis: "PERKIM",
    c_driver: "Sukamto",
    c_fkali: 1.5,
  },
  {
    c_nopol: "H 9584 FE",
    c_kendaraan: "PICKUP",
    c_jenis: "PERKIM",
    c_driver: "Fangkaliana",
    c_fkali: 1.5,
  },
  {
    c_nopol: "H 9598 HE",
    c_kendaraan: "LAINNYA",
    c_jenis: "PERKIM",
    c_driver: "Agus ",
    c_fkali: 7,
  },
  {
    c_nopol: "H 9581 FE",
    c_kendaraan: "TRUK KAYU",
    c_jenis: "PERKIM",
    c_driver: "Kuswanto",
    c_fkali: 8,
  },
  {
    c_nopol: "H 9545 EE",
    c_kendaraan: "DUMP TRUCK",
    c_jenis: "PERKIM",
    c_driver: "Beni",
    c_fkali: 7,
  },
];
