export const DEMAKLOC = [-6.8909, 110.6396];
export const DATAKECAMATAN = [
  { id: " PILIH", DESA: ["PILIH"] },
  {
    id: " Bonang",
    DESA: [
      "PILIH",
      "Bonangrejo",
      "Gebang",
      "Gebangarum",
      "Jali",
      "Jatimulyo",
      "Jatirogo",
      "Karangrejo",
      "Kembangan",
      "Krajanbogo",
      "Margolinduk",
      "Morodemak",
      "Poncoharjo",
      "Purworejo",
      "Serangan",
      "Sukodono",
      "Sumberejo",
      "Tlogoboyo",
      "Tridonorejo",
      "Weding",
      "Wonosari",
    ],
  },
  {
    id: " Demak",
    DESA: [
      "PILIH",
      "Bolo",
      "Cabean",
      "Donorejo",
      "Kalikondang",
      "Karangmlati",
      "Katonsari",
      "Kedondong",
      "Mulyorejo",
      "Raji",
      "Sedo",
      "Tempuran",
      "Turirejo",
      "Betokan",
      "Bintoro",
      "Kadilangu",
      "Kalicilik",
      "Mangunjiwan",
      "Singorejo",
    ],
  },
  {
    id: " Dempet",
    DESA: [
      "PILIH",
      "Baleromo",
      "Botosengon",
      "Brakas",
      "Dempet",
      "Gempoldenok",
      "Harjowinangun",
      "Jerukgulung",
      "Karangrejo",
      "Kebonsari",
      "Kedungori",
      "Kramat",
      "Kunir",
      "Kuwu",
      "Merak",
      "Sidomulyo",
    ],
  },
  {
    id: " Gajah",
    DESA: [
      "PILIH",
      "Boyolali",
      "Gajah",
      "Gedangalas",
      "Jatisono",
      "Kedondong",
      "Medini",
      "Mlatiharjo",
      "Mlekang",
      "Mojosimo",
      "Sambiroto",
      "Sambung",
      "Sari",
      "Surodadi",
      "Tambirejo",
      "Tanjunganyar",
      "Tlogopandogan",
      "Wilalung",
    ],
  },
  {
    id: " Guntur",
    DESA: [
      "PILIH",
      "Banjarejo",
      "Blerong",
      "Bogosari",
      "Bumiharjo",
      "Gaji",
      "Guntur",
      "Krandon",
      "Pamongan",
      "Sarirejo",
      "Sidoharjo",
      "Sidokumpul",
      "Sukorejo",
      "Tangkis",
      "Temuroso",
      "Tlogorejo",
      "Tlogoweru",
      "Trimulyo",
      "Turitempel",
      "Wonorejo",
    ],
  },
  {
    id: " Karanganyar",
    DESA: [
      "PILIH",
      "Cangkring",
      "Cangkring Rembang",
      "Jatirejoo",
      "Karanganyar",
      "Kedungwaru Kidul",
      "Kedungwaru Lor",
      "Ketanjung",
      "Kotakan",
      "Ngaluran",
      "Ngemplik Wetan",
      "Tugu Lor",
      "Tuwang",
      "Undaan Kidul",
      "Undaan Lor",
      "Wonoketingal",
      "Wonorejo",
    ],
  },
  {
    id: " Karangawen",
    DESA: [
      "PILIH",
      "Bumirejo",
      "Jragung",
      "Karangawen",
      "Kuripan",
      "Margohayu",
      "Pundenarum",
      "Rejosari",
      "Sido Rejo",
      "Teluk",
      "Tlogorejo",
      "Wonosekar",
    ],
  },
  {
    id: " Karangtengah",
    DESA: [
      "PILIH",
      "Donorejo",
      "Dukun",
      "Grogol",
      "Karangsari",
      "Karangtowo",
      "Kedunguter",
      "Klitih",
      "Pidodo",
      "Ploso",
      "Pulosari",
      "Rejosari",
      "Sampang",
      "Tambakbulusan",
      "Wonoagung",
      "Wonokerto",
      "Wonowoso",
    ],
  },
  {
    id: " Kebonagung",
    DESA: [
      "PILIH",
      "Kebonagung",
      "Klampok Lor",
      "Mangunan Lor",
      "Mangunrejo",
      "Megonten",
      "Mijen",
      "Pilangwetan",
      "Prigi",
      "Sarimulyo",
      "Soko Kidul",
      "Solowire",
      "Tlogosih",
      "Werdoyo",
    ],
  },
  {
    id: " Mijen",
    DESA: [
      "PILIH",
      "Banteng Mati",
      "Bermi",
      "Gempolsongo",
      "Geneng",
      "Jleper",
      "Mijen",
      "Mlaten",
      "Ngegot",
      "Ngelo Kulon",
      "Ngelo Wetan",
      "Pasir",
      "Pecuk",
      "Rejosari",
      "Tanggul",
    ],
  },
  {
    id: " Mranggen",
    DESA: [
      "PILIH",
      "Banyumeneng",
      "Batursari",
      "Brumbung",
      "Candisari",
      "Jamus",
      "Kalitengah",
      "Kangkung",
      "Karangsono",
      "Kebonbatur",
      "Kembangarum",
      "Menur",
      "Mranggen",
      "Ngemplak",
      "Sumberejo",
      "Tamansari",
      "Tegalarum",
      "Waru",
      "Wringin Jajar",
    ],
  },
  {
    id: " Sayung",
    DESA: [
      "PILIH",
      "Bedono",
      "Bulusari",
      "Dombo",
      "Gemulak",
      "Jetaksari",
      "Kalisari",
      "Karangasem",
      "Loireng",
      "Perampelan",
      "Pilangsari",
      "Purwosari",
      "Sayung",
      "Sidogemah",
      "Sidorejo",
      "Sriwulan",
      "Surodadi",
      "Tambakroto",
      "Timbulsloko",
      "Tugu",
    ],
  },
  {
    id: " Wedung",
    DESA: [
      "PILIH",
      "Berahan Kulon",
      "Berahan Wetan",
      "Buko",
      "Bungo",
      "Jetak",
      "Jungpasir",
      "Jungsemi",
      "Kedungkarang",
      "Kedungmutih",
      "Kendalasem",
      "Kenduren",
      "Mandung",
      "Mutih Kulon",
      "Mutih Wetan",
      "Ngawen",
      "Ruwit",
      "Tedunan",
      "Tempel",
      "Wedung",
    ],
  },
  {
    id: " Wonosalam",
    DESA: [
      "PILIH",
      "Bunderan",
      "Doreng",
      "Getas",
      "Jogoloyo",
      "Kalianyar",
      "Karangrejo",
      "Karangrowo",
      "Kendaldoyong",
      "Kerangkulon",
      "Kuncir",
      "Lempuyang",
      "Mojodemak",
      "Mranak",
      "Mrisen",
      "Pilangrejo",
      "Sido Mulyo",
      "Tlogodowo",
      "Tlogorejo",
      "Trengguli",
      "Wonosalam",
    ],
  },
];
